# Generated by Django 4.0.4 on 2022-05-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_service', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='TypeMedia',
        ),
        migrations.AddField(
            model_name='service',
            name='type_de_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.typeservice'),
        ),
    ]
