# Generated by Django 4.0.4 on 2022-05-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_typeservice_rename_type_typemedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrs',
            name='mail',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactrs',
            name='page_facebook',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactrs',
            name='skype',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactrs',
            name='whatsapp',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
